### ISSUE TITLE
Need to add additional maven url for "merge" dependency

### ISSUE THREAD

**Issue by ka05** [abacritt/sectionedmergeadapter#1]
When adding the dependency to my project i got the following error which was based on the **com.commonsware.cwac:merge** dependency. 

Error
`Error:Failed to resolve: com.commonsware.cwac:merge:1.1.1`

In order to fix it i had to add the maven repo for **cwac merge**
```
repositories {
    maven { url "https://jitpack.io" } // sectioned merge adapter
    maven { url "https://s3.amazonaws.com/repo.commonsware.com" } // had to add this guy
}
```

**Comment by jaibatrik** [comment]
Thanks for pointing out! I'll add this to the README file.
