### ISSUE TITLE
ListView crash after certain number of strings, showing only the firts 12 items

### ISSUE THREAD

**Issue by hitmacreeed** [abacritt/sectionedmergeadapter#2]
Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView

**Comment by hitmacreeed** [comment]
Failed to find view with ID android:id/text1 in item layout

**Comment by hitmacreeed** [comment]
<string-array name="turi">
        <item>Rua Cor-de-Rosa</item>
        <item>Parque Eduardo VII </item>
        <item>Avenida da Liberdade</item>
        <item>Sé de Lisboa</item>
        <item>Panteão Nacional</item>
        <item>Miradouro da Graça</item>
        <item> Miradouro Portas do Sol</item>
        <item>Ponte 25 de Abril</item>
        <item>Bairro Alto</item>
        <item>Miradouro Nossa Senhora do Monte</item>
        
        <item>Casa dos Bicos</item>
        <item>Praça do Comércio</item>
        <item>Torre de Belém</item>
        <item>Mosteiro de Jerónimo</item>
        <item>Elevador de Santa Justa</item>
        <item>Santuário Nacional do Cristo Rei</item>
        <item>Parque das Nações</item>
        <item>Palácio da Pena</item>
        <item>Quinta da Regaleira</item>
        <item>Museo do Dinheiro</item>
        <item>Museu do Fado</item>
        <item>MAAT</item>
  </string-array>

String[] turista;

 ListView listView = (ListView) findViewById(android.R.id.list);

 ArrayAdapter<String> adapter4 = new ArrayAdapter<>(this, R.layout.item_list, android.R.id.text1, turista);

 LinearLayout spots =  getLayoutInflater().inflate(R.layout.item_header4, null, false).findViewById(R.id.turistico);


  adapter.addSection(new SectionedMergeAdapter.Section(spots, adapter4));

 listView.setAdapter(adapter);

**Comment by jaibatrik** [comment]
Can you create a basic sample project showing the issue and upload it to Github and share it with us?

**Comment by hitmacreeed** [comment]
i solved the issue by spliting the String array in 2! thanks
